### ISSUE TITLE
Not able to change the lang

### ISSUE THREAD

**Issue by shamimsdp** [lukszymanski/digit-words#3] opened 2020-07-25 11:33 UTC
I'm trying to change the language to English but not able to change it.

**Comment by lukszy** [comment] 2020-07-26 07:32
hi, couldn't reproduce the problem. Could You provide a snippet or step by step to reproduce?

**Comment by lukszy** [comment] 2020-08-21 05:59
closing as i cannot reproduce this issue and no info added

**Closed as completed by lukszy** 2020-08-21 05:59 UTC
